version = 1

exclude_patterns = ["testCommands.go"]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/chand1012/Discord-Quick-Meme"]

[[transformers]]
name = "gofmt"
enabled = true