if: branch = master
sudo: true
language: go
go:
- 1.10.x
os:
- linux
before_script:
- go get github.com/bwmarrin/discordgo
- go get github.com/turnage/graw
script:
- go build -v -o GoDiscordBot
deploy:
  provider: releases
  api_key:
    secure: 3gxpc5GWQcl7tUoSU7+EFZxkHg3YR8mG1+x4Axxj8F1bGbi9gRhUAbX/CUyqcR+3PxdK7V/YIQ+YbVImZuSFZPq/aDPbhVBaukEnuyACZGo1t1AwmYxbimxK+aYdpCgDLbV3y4HEg+jJ2fXQcCtQuyM1xiwKwR3eHJbkK6eAmGSHMfK5jiRy4z6eNbIl8MohiMyFw6ySXQ3URap6J3fFTjrPC61aJdjLF3p67ls4Ghd3apCxoIScHEjxQ9Y1nL2IgnL+IeZ7glX4EM/sZYObyUaxzATNy9c5NfsIZ7M7l890WpWuRq3sNo+XgX2cFNk1TJFcYIp/W72jpFi3W+tvoPjR/vrAqe6UKKv+aR4/Suq4iLI99JO4fBkULSJ6N5x557zAnCsM5HW75rJBxhgdNrBZDI9t8OBgsgf6fSwFU4wkRjko0Pr+YEJ1eXNF2BIM1X6WVBnM/cc2PD65Desoyvp7JK5/LaQogxTEporXjj1TkWeFJswRmqztC5gd8TwLSmRRtPH/Eg/BaU/oXoO8Gz2ctzQhsi/iTGd6ux6R2xuTT3s1ZfB26jtNAEwwK9MgiCWy1HlMNRLN6c9A9MLfCGqiAYxruq94OsTBvsI/tOzh2AFPXAxp0QS8QI3osi5YHiRvNF3M3bUdLOPhwrELrslMyflgoOEkb/TCvciM0zo=
  file: GoDiscordBot
  skip_cleanup: true
  draft: true
  overwrite: true
