if: branch = master
sudo: false
language: go
go:
  - 1.10.x
os:
  - linux

before_script:
  - go get github.com/bwmarrin/discordgo
  - go get github.com/turnage/graw
script: 
  - go build -v -o GoDiscordBot
after_success:
  - echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
  - curl --ftp-create-dirs
       -T GoDiscordBot
       --key /tmp/sftp_rsa
       sftp://${SFTP_USER}:${SFTP_PASSWORD}@${SFTP_IP}:${SFTP_PORT}/home/${SFTP_USER}/GoDiscordBot