if: branch = master
sudo: true
language: go
go:
  - 1.10.x
os:
  - linux

before_script:
  - go get github.com/bwmarrin/discordgo
  - go get github.com/turnage/graw
  - apt update
  - apt install sshpass -y
script: 
  - go build -v -o GoDiscordBot
after_success:
  - ssh-keygen -b 2048 -t rsa -f /tmp/sshkey -q -N ""
  - sshpass -p "${SFTP_PASSWORD}" scp GoDiscordBot -P ${SFTP_PORT} ${SFTP_USER}@${SFTP_IP}:/home/${SFTP_USER}/GoDiscordBot