if: branch = master
sudo: true
language: go
go:
- 1.10.x
os:
- linux
before_script:
- go get github.com/bwmarrin/discordgo
- go get github.com/turnage/graw
script:
- go build -v -o GoDiscordBot
deploy:
  provider: releases
  api_key:
    secure: Es/9fXDf0U7B9C0Muf4Q2JDysxTC2MP44FFCsIcvT+p93xXGjrvTW+p3+qA0ZB3+rrGR6NH6Ict/ZwMfn2TrfFWul6XuCGz+BR3H56wMrwK/pgY9ZSxsmw0pqm502CBg40tfbrNeoOnAnAaJeNBWHm3Hz61/Gr3rI1aQim/Tf+oGlS2S6io/LsvBdbM8JHOqbTj3yd9Ux33tee39lcxzW88NCJNlR7t9HzL/Ai2AYg/UfUULSgrnOvAlnBtOBpX7PnliH+dmECcD9/tjlbSoPNVR7U+0pmW9aHhNLrtDEr9uGoC1MtclERTkIESIKpzdZn3p832oQ+mi+LHJQX5QDdnxsqqW8wQV61jHtsSfDqZHGPoq0+RzBLTuC85CPbrDC71wgSTv51wqFpcSIcl6cm9LecvrU3Auna+MPFIuQbdk0TwWS23OaJro4ySh8WQQgQlNbQz/gcUxYUUPoqtgQt13H7QKAZvcnkF4XBU5vFQ+ywSk9WMWd2nCzyRKYgCbHJKSEqA3qkA2Hg57h5975V/BZBgS1JCX1oKMNOc2aGBIgY5UceEU/mciYeVMIQ2qGD3uuKOxkTAxtgPGxvUpD3rZKiYvb4nKYXoUHurEp52jAcxuX/2aWBdp3V3roMOX858L1il88S+sb1y+pGTn3IfMHbK4KJAH1Oa839JzN1M=
  file: GoDiscordBot
  skip_cleanup: true
  draft: true
  overwrite: true
