name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Build Image
      run: |
       docker login docker.pkg.github.com -u chand1012 --password ${{ secrets.PASSWORD }}
       docker build -t discord-quick-meme:${{ steps.extract_branch.outputs.branch }} .
       docker push docker.pkg.github.com/chand1012/discord-quick-meme/discord-quick-meme:${{ steps.extract_branch.outputs.branch }}
